//============================================================
// Scoring controller
//
// Acts as an intelligent middle-man to the problem state model, which
// is just a dumb data repository.
//
// Rather than duplicating a lot of fields from the problem in the state,
// the state will have access to the problem model.  That is hardly ideal,
// creating an overly tight coupling between the two.  Given that so much
// information is required, and that the score may need to be changed,
// it seems expedient to just do it this way for now.
//
// Controls scoring (points, stars), next/similar question behavior, and text responses
//============================================================
;(function()
{
	// Actions API:
	// TEXT: Display a message.  Parameters: text, color
	// STEPTEXT: Display a message under the last step.  Parameters: text, color
	// GLOBALTEXT: Display a message at the top level, not inside step-by-step (if it's active).  Parameters: text, color
	// NOCHECK: Disable Check (student can't submit another answer until it gets reenabled externally)
	// SOLUTION: Show solution.  Parameter: Solution shown by request (vs. shown for a correct or incorrect answer)
	// NEXT: Next question
	// SIMILAR: Similar question
	// CHOICE: Next or similar question (user choice)
	// NEXTSTEP: Advance to the next step in step-by-step mode
	// LASTSTEP: The last step was completed.
	// REMOVE: Remove this base question from the list, i.e. the user can't work on it anymore
	// FAIL: Increase the failure count
	// FAILOUT: Remove this base question from the list, and mark it as Failed/No Credit
	// SET_STATUS: Set the status indicator.  Parameter: status (New, Correct, Wrong, Locked)
	// STREAK_INC: Streak increased.  Client event (doesn't change the state, which happens elsewhere).
	// STREAK_RESET: Streak reset
	// REWARD: Client event
	// WRONG: Client event
	// LOCK: Immediately fail out of a problem
	// DISABLE_INPUT: deal with last submission of wrong answer.
	// SHOWGRAPH: Display the solution only for graph questions
	// RESTOREINPUT: Reenable input buttons
	// SUBMIT: Use up a submission
	// NEXTSTEP: Move to the next step
	// SUBMITSTEP: Increases the submission count
	// STEPSOLUTION: Show the solution for the current step
	// STEP_STATUS: Set the status for the current step
	// CLEANSTEP: "Clean up" the current step -- remove buttons, go to compact mode

	var happyColor = app.style.happyColor;
	var sadColor = app.style.sadColor;
	var defaultColor = app.style.defaultColor;

	var helper = app.scoring.helpers;

	var feedbackText;		// Temp global variable

	var scriptList = {

	//----------------------------------------
	// Finalize (top-level)
	//----------------------------------------

		// Correct
		// Also: Correct, final step in step-by-step mode
		correctLastStep: [
			"SUBMITSTEP",
			"STEP_STATUS", "Correct",
//			"STEPSOLUTION",
			"CLEANSTEP",

			"TEXT", happyColor, "All parts have been completed. Please continue with the next question.",
			"SET_STATUS", "multiPart",
			"REWARD",
			"SHOWGRAPH",
			"NEXT"
		],

		wrongLastTryLastStep: [
			"SUBMITSTEP",
			"STEP_STATUS", "Locked",
			"STEPSOLUTION",
			"CLEANSTEP",

			"DISABLE_INPUT",
			"TEXT", sadColor, "All parts have been completed. Please continue with the next question.",
			"WRONG",
			"SET_STATUS", "multiPart",
			"NEXT"
		],

		pendingLastStep: [
			"SUBMITSTEP",
			"STEP_STATUS", "Pending",
			"CLEANSTEP",

			"SET_STATUS", "multiPart",
			"TEXT", defaultColor, "All parts have been completed. Please continue with the next question.",
			"NEXT"
		],

	//----------------------------------------
	// Generated by submitting a wrong answer
	//----------------------------------------

		// A single step (not the final step) is correct
		correctStep: [
			"SUBMITSTEP",
			"STEPTEXT", happyColor, "That is correct!",
			"REWARD",
			"STEP_STATUS", "Correct",
			"SET_STATUS", "multiPart",
	"STEPSOLUTION",				// @FIXME/dg: This probably isn't right. It's better to leave the user's correct answer. However, this removes the boxes from free inputs, for consistency.
			"RESTOREINPUT",		// This needs to occur before NEXTSTEP, or the buttons are gone
			"NEXTSTEP"
		],

		// Step, wrong answer, first or second time wrong
		wrongStep: [
			"SUBMITSTEP",
			"STEPTEXT", sadColor, "Try again. Choose a help option for more hints to solve the problem.",
			"RESTOREINPUT",		// This needs to occur before WRONG or focus can't properly be set
			"WRONG",
			"STEP_STATUS", "Wrong"
		],

		wrongLastTry: [
			"SUBMITSTEP",
			"STEPTEXT", sadColor, "The solution to this part is shown. You don't get any credit for this part.",
			"WRONG",
			"STEP_STATUS", "Locked",
			"SET_STATUS", "multiPart",
			"STEPSOLUTION",
			"NEXTSTEP"
		],

	//----------------------------------------
	// Generated by a pending state for problems
	// that require teacher grading.
	//----------------------------------------
		pendingStep: [
			"SUBMITSTEP",
			"STEPTEXT", defaultColor, "Your answer has been submitted. You will receive a grade as soon as your teacher reviews it.",
			"STEP_STATUS", "Pending",
			"SET_STATUS", "multiPart",
			"NEXTSTEP"
		],

	//----------------------------------------
	// Generated by viewing a solution
	//
	// Only available temporarily, for Test mode.
	//----------------------------------------

		// User viewed the solution
		viewSolution: [
			"GLOBALTEXT", sadColor, "Study the solution. You received no credit for this problem.",
			"SET_STATUS", "Locked",
			"SOLUTION", true,
			"SIMILAR"
		],

	//----------------------------------------
	// Incorrect with helpful feedback
	//----------------------------------------
		feedback: [
			"TEXT", sadColor, function() {
				return feedbackText;
			},
			"RESTOREINPUT"
		],

		feedbackStep: [
			"STEPTEXT", sadColor, function() {
				return feedbackText;
			},
			"RESTOREINPUT"
		]
	};

//==========================================================================
// Helpers
//==========================================================================
	//=======================================================
	//
	//=======================================================
	function formatScore(num)
	{
		num = parseFloat(num);
		return parseFloat(num.toFixed(2));
	}

//==========================================================================
// Action/Response Model
//==========================================================================

	//=======================================================
	//=======================================================
	app.scoring.MultiPartHW = {
		correct: correctLastStepAction,		// Can't occur
		correctStep: correctStepAction,
		correctLastStep: correctLastStepAction,

		wrong: wrongStepAction,				// Can't occur
		wrongStep: wrongStepAction,
		wrongLastStep: wrongLastStepAction,

		pending: pendingAction,				// Can't occur
		pendingStep: pendingAction,
		pendingLastStep: pendingLastStepAction,

		feedback: feedbackAction,			// Can't occur
		feedbackStep: feedbackStepAction,
		feedbackLastStep: feedbackStepAction,

		solution: solutionAction,
	};

	//=======================================================
	// Determines the appropriate action given a correct answer
	//=======================================================
	function correctLastStepAction()
	{
		return scriptList.correctLastStep;
	}

	//=======================================================
	// Determines the appropriate action given a correct answer (step-by-step mode)
	//=======================================================
	function correctStepAction()
	{
		if (helper.get('curStep') >= (helper.pget('solve').length - 1))
			return correctAction();	// All steps complete -- Use main answer actions
		else
			return scriptList.correctStep;
	}

	//=======================================================
	// Determines the appropriate action given a wrong answer
	//=======================================================
	function wrongLastStepAction()
	{
		// Only one attempt is allowed for radio inputs
		if (helper.answerType(true) === 'radio')
			return scriptList.wrongLastTryLastStep;

		var step = helper.pget('solve')[helper.get('curStep')];
		var submits = step.submissions*1 + 1;	// The problem was just submitted.  The submission count is now 1 higher.
		var maxSubs = app.getMaxSubmissions();

		if (submits < maxSubs)
			return scriptList.wrongStep;
		else
			return scriptList.wrongLastTryLastStep;
	}

	//=======================================================
	// The question was answered incorrectly.
	//=======================================================
	function wrongStepAction()
	{
		// Only one attempt is allowed for radio inputs
		if (helper.answerType(true) === 'radio')
			return scriptList.wrongLastTry;

		var step = helper.pget('solve')[helper.get('curStep')];
		var submits = step.submissions*1 + 1;	// The problem was just submitted.  The submission count is now 1 higher.
		var maxSubs = app.getMaxSubmissions();

		if (submits < maxSubs)
			return scriptList.wrongStep;
		else
			return scriptList.wrongLastTry;
	}

	//=======================================================
	// Determines the appropriate action given a pending state
	// for a submission.
	//=======================================================
	function pendingAction()
	{
		return scriptList.pendingStep;
	}

	//=======================================================
	// Determines the appropriate action given a pending state
	// for a submission.
	//=======================================================
	function pendingLastStepAction()
	{
		return scriptList.pendingLastStep;
	}

	//=======================================================
	// This should never be called for online homework.
	// However, the routine is necessary for the API.
	//=======================================================
	function solutionAction()
	{
		return scriptList.viewSolution;
	}

	//=======================================================
	// The answer was incorrect, but we don't count it as
	// wrong. Instead we supply helpful feedback.
	//=======================================================
	function feedbackAction(msg)
	{
		feedbackText = msg;		// Slightly dangerous, but we're not reentrant
		return scriptList.feedback;
	}

	//=======================================================
	// The answer was incorrect, but we don't count it as
	// wrong. Instead we supply helpful feedback.
	//=======================================================
	function feedbackStepAction(msg)
	{
		feedbackText = msg;		// Slightly dangerous, but we're not reentrant
		return scriptList.feedbackStep;
	}

})();
